# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  java-image:
    working_directory: ~/repo
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m
    docker:
      - image: docker.cloudsmith.io/autonomic/public-images/java
        auth:
          username: ${CS_PUBLIC_USERNAME}
          password: ${CS_PUBLIC_API_TOKEN}
  snapshot-publisher-image:
    working_directory: ~/repo
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m
    docker:
      - image: docker.cloudsmith.io/autonomic/private-images/java
        auth:
          username: ${CS_PUBLIC_USERNAME}
          password: ${CS_PUBLIC_API_TOKEN}
  gitleaks-image:
    working_directory: ~/repo
    docker:
      - image: docker.cloudsmith.io/autonomic/private-images/gitleaks
        auth:
          username: ${CS_PRIVATE_USERNAME}
          password: ${CS_PRIVATE_API_TOKEN}
jobs:
  scan_secrets:
    executor: gitleaks-image
    steps:
      - checkout
      - run: gitleaks
  build:
    executor: java-image
    steps:
    - checkout
    - run: mvn clean
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "pom.xml" }}-{{ checksum "tmc-oss-license/pom.xml" }}-{{ checksum "tmc-oss-parent/pom.xml" }}
    - run: |
        mvn dependency:go-offline
        mvn package
    - save_cache:
        paths:
        - ~/.m2
        key: v3-dependencies-{{ checksum "pom.xml" }}-{{ checksum "tmc-oss-license/pom.xml" }}-{{ checksum "tmc-oss-parent/pom.xml" }}
    - persist_to_workspace:
        root: /root
        paths:
          - repo
          - .m2

  #publish artifact to OSS repo
  publish-public:
    executor: java-image
    steps:
      - attach_workspace:
          at: /root
      - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run:
          name: Publish to tmc-oss-root-pom
          command: /root/publish.sh publish_public

  private-snapshot-dependency-track:
    executor: snapshot-publisher-image
    working_directory: /root/repo
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: set new version
          command: mvn versions:set -DnewVersion=LATEST-SNAPSHOT
      - run:
          name: Publish tmc-oss-root-pom-private to au-tmc-snapshots
          command: /root/publish.sh publish_snapshot
      - run:
          name: Upload to Dependency Track
          command: mvn validate -Ddependency-track.projectName=${CIRCLE_PROJECT_REPONAME} -Pdependency-track

  dependency-track:
    executor: java-image
    steps:
      - attach_workspace:
          at: /root
      - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run:
          name: Upload to Dependency Track
          command: mvn validate -Ddependency-track.projectName=${CIRCLE_PROJECT_REPONAME} -Pdependency-track

  push-to-public:
    executor: snapshot-publisher-image
    steps:
      - checkout
      - run:
          name: Push to public repo
          command: /root/publish.sh push_public tmc-oss-root-pom ${CIRCLE_BRANCH} ${CIRCLE_BRANCH}

workflows:
  version: 2
  build_and_test:
    jobs:
    - scan_secrets:
        context: tmc-cloudsmith-context
    - build:
        context: tmc-cloudsmith-context
        requires:
          - scan_secrets
    - private-snapshot-dependency-track:
        context:
          - tmc-cloudsmith-context
          - tmc-oss-context
        requires:
          - build
        filters:
          branches:
            only: rc
    - push-to-public:
        context:
          - tmc-cloudsmith-context
          - tmc-oss-context
        requires:
          - build
        filters:
          branches:
            only:
              - main
              - /release\/.*/
  release:
    jobs:
      - scan_secrets:
          context: tmc-cloudsmith-context
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - scan_secrets
          context:
            - tmc-cloudsmith-context
    #Run Publish on GitHub release
      - publish-public:
          context:
            - tmc-cloudsmith-context
            - tmc-oss-context
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - dependency-track:
          context:
            - tmc-cloudsmith-context
            - tmc-oss-context
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/