# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: autonomic-docker-circle-ci-images.bintray.io/tmc-oss/java-ci
        auth:
          username: ${BT_OSS_USER}
          password: ${BT_OSS_API_KEY}

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v3-dependencies-

    - run: mvn dependency:go-offline

    - run: mvn clean package

    - save_cache:
        paths:
        - ~/.m2
        key: v3-dependencies-{{ checksum "pom.xml" }}


  #publish artifact to artifactory repo
  publish:
    docker:
      - image: autonomic-docker-circle-ci-images.bintray.io/tmc-oss/java-ci
        auth:
          username: ${BT_OSS_USER}
          password: ${BT_OSS_API_KEY}

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v3-publish-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v3-publish-dependencies-
    - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
    - run: mvn deploy


workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        context: tmc-oss-context
  release:
    jobs:
    #Run Publish on GitHub release
    - publish:
        context: tmc-oss-context
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/
