# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker.cloudsmith.io/autonomic/public-images/java
        auth:
          username: ${CS_PUBLIC_USERNAME}
          password: ${CS_PUBLIC_API_TOKEN}

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
    - checkout

    - run: mvn clean 

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "pom.xml" }}-{{ checksum "tmc-oss-license/pom.xml" }}-{{ checksum "tmc-oss-parent/pom.xml" }}

    - run: mvn dependency:go-offline 

    - run: mvn package 

    - save_cache:
        paths:
        - ~/.m2
        key: v3-dependencies-{{ checksum "pom.xml" }}-{{ checksum "tmc-oss-license/pom.xml" }}-{{ checksum "tmc-oss-parent/pom.xml" }}


  #publish artifact to artifactory repo
  publish-public:
    docker:
      - image: docker.cloudsmith.io/autonomic/public-images/java
        auth:
          username: ${CS_PUBLIC_USERNAME}
          password: ${CS_PUBLIC_API_TOKEN}

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "pom.xml" }}-{{ checksum "tmc-oss-license/pom.xml" }}-{{ checksum "tmc-oss-parent/pom.xml" }}
    - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
    - run: mvn deploy -Ppublic

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
  release:
    jobs:
    #Run Publish on GitHub release
    - publish-public:
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/